### PR TITLE
Key Vault clients discover auth parameters

### LINKED ISSUE #3309: Key Vault clients use hardcoded public cloud scope
### Bug Title

_No response_

### Crate Name

azure_security_keyvault_secrets

### Crate Version

0.9.0

### Description

Current secret client has a fixed auth policy restricting the access to Azure Government 

1. create secret on keyvault for Azure Gov
2. Instantiate a client for Azure Goverment cloud 
3. Try to get the secret using get_secret method
4. it fails with the following message: The requested identity hasn’t been assigned to this resource.

The code responsible for the error:

https://github.com/Azure/azure-sdk-for-rust/blob/7583705b45797a8f53d474f1272d0f890a902444/sdk/keyvault/azure_security_keyvault_secrets/src/generated/clients/secret_client.rs#L71-L74

### Steps to Reproduce

1. create secret on keyvault for Azure Gov
2. Instantiate a client for Azure Goverment cloud 
3. Try to get the secret using get_secret method
4. it fails with the following message: The requested identity hasn’t been assigned to this resource.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/Azure/azure-sdk-for-rust/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by chlowell**
This adds support for non-Public clouds (closes #3309) and enables multi-tenant scenarios. Implementation follows that of the other SDKs: clients send their first request without authorization to elicit an authentication challenge specifying the audience (scope) and tenant for the Vault (clients use only the audience today; #3471 tracks the work required to use the tenant). After parsing the parameters, clients cache them and authorize and retry the request. We don't have a great way to share code across Key Vault crates, so I've just copied the implementation (authorizer.rs) into each.

### CODE REVIEW

File: sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs [hunk 1]
```diff
@@ -13,5 +14,77 @@ mod generated;
...
+use std::sync::Arc;
+
+/// Options used when creating a [`CertificateClient`]
+#[derive(Clone, SafeDebug)]
+pub struct CertificateClientOptions {
+    /// The API version to use for this operation.
+    pub api_version: String,
+    /// Allows customization of the client.
+    pub client_options: ClientOptions,
+}
```
Comment (heaths) [inline sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs]: This must be defined in the `src/clients.rs` file (`clients` module) and re-exported here.

File: sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs [hunk 2]
```diff
@@ -13,5 +14,77 @@ mod generated;
...
+impl Default for CertificateClientOptions {
+    fn default() -> Self {
+        Self {
+            api_version: String::from("2025-07-01"),
+            client_options: ClientOptions::default(),
+        }
+    }
+}
+
+impl CertificateClient {
```
Comment (heaths) [inline sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs]: All implementations should also be centralized in the `clients` module i.e., `src/clients.rs`. That's guidelines.

File: sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs [hunk 3]
```diff
@@ -13,5 +14,77 @@ mod generated;
...
+    /// The API version to use for this operation.
+    pub api_version: String,
+    /// Allows customization of the client.
+    pub client_options: ClientOptions,
+}
+
+impl Default for CertificateClientOptions {
+    fn default() -> Self {
+        Self {
+            api_version: String::from("2025-07-01"),
```
Comment (heaths) [inline sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs]: @jhendrixMSFT this is one thing I hadn't considered when we talked about this last month. This means that whenever a new api-version is added, authors will have to remember to update this code manually.

Should we instead define a `pub(crate) DEFAULT_API_VERSION: &str = "2025-07-01"`, for example, in `src/generated/mod.rs` or something that we not only use in the generated `impl Default for *ClientOptions` but can be used by anyone like these instances?

/cc @RickWinter @LarryOsterman

File: sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs [hunk 4]
```diff
@@ -13,5 +14,77 @@ mod generated;
...
+            return Err(azure_core::Error::with_message(
+                azure_core::error::ErrorKind::Other,
+                format!("{endpoint} must use http(s)"),
+            ));
+        }
+        let authorizer = authorizer::KeyVaultAuthorizer::new();
+        let auth_policy: Arc<dyn Policy> = Arc::new(
+            BearerTokenAuthorizationPolicy::new(credential, Vec::<String>::new())
+                .with_on_request(authorizer.clone())
+                .with_on_challenge(authorizer),
```
Comment (heaths) [inline sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs]: This seems wasteful, even though it's an `Arc`. Is it only an `Arc` returned from `new` because of this? Assuming most will use the same instance, could one or the other method assume to use the same instance internally to avoid? It's not a blocker - not *that* wasteful - but seems that the default case (I assume) will always require two `Arc`s that point to the same instance.

File: sdk/keyvault/azure_security_keyvault_certificates/src/authorizer.rs
Comment (heaths) [inline sdk/keyvault/azure_security_keyvault_certificates/src/authorizer.rs:1]: @weshaggard we need to share source in some cases like this. What are your thoughts on symlinks, which git supports? Unlike .NET, Rust has no good way to share source like we do for .NET.

File: sdk/keyvault/azure_security_keyvault_certificates/src/authorizer.rs [hunk 5]
```diff
@@ -0,0 +1,484 @@
...
+                        } else {
+                            format!("{value}/.default")
+                        });
+                    }
+                }
+            }
+        }
+
+        Err(Error::with_message(
+            ErrorKind::Other,
```
Comment (heaths) [inline sdk/keyvault/azure_security_keyvault_certificates/src/authorizer.rs]: Should this be `ErrorKind::Credential`? Or is that mostly reserved for actual auth issues and not necessarily bad response data? Is there a distinction in this case, though?

File: sdk/keyvault/azure_security_keyvault_certificates/src/authorizer.rs [hunk 6]
```diff
@@ -0,0 +1,484 @@
...
+    async fn on_request(
+        &self,
+        ctx: &mut Context,
+        request: &mut Request,
+        authorizer: &dyn Authorizer,
+    ) -> azure_core::Result<()> {
+        let scope = self.scope.read().await;
+        if scope.is_empty() {
+            if !request.body().is_empty() {
+                ctx.insert(request.body().clone());
```
Comment (heaths) [inline sdk/keyvault/azure_security_keyvault_certificates/src/authorizer.rs]: This could be expensive. We already have a `Request::body_mut()` I added late last year that will give you a `&mut Body`. I'd be open to a `Body::take(&mut self) -> Body` that, for a `Bytes` buffer, returns an owned `Body::Bytes(Bytes)` leaving an empty buffer in its place much like `Option::take(&mut self)`.

For a `SeekableStream`, since we actually wrap it with a `Box` we could do much the same. Would be cheaper and not copy memory.

File: sdk/keyvault/azure_security_keyvault_certificates/src/authorizer.rs
Comment (heaths) [reply sdk/keyvault/azure_security_keyvault_certificates/src/authorizer.rs:1]: Talked to @weshaggard and he was fine with trying, but I'd make keys's file the primary for reasons we discussed internally.

File: sdk/keyvault/azure_security_keyvault_certificates/src/authorizer.rs (hunk 5 above)
Comment (chlowell) [reply sdk/keyvault/azure_security_keyvault_certificates/src/authorizer.rs]: In my mind, `ErrorKind::Credential` implies an authentication failure and is useful primarily as advice to the application not to retry a client method call. Should this be `ErrorKind::DataConversion`?

Comment (heaths) [reply sdk/keyvault/azure_security_keyvault_certificates/src/authorizer.rs]: `DataConversion` is better than `Other`, yeah, but this still feels like an auth issue. The server gave bad response data, sure, but that would prevent authenticating.

I don't have a strong feeling either way, so unless @RickWinter or @ronniegeraghty do I leave it up to you. We might want to codify our stance in the guidelines just for reference, though: not strictness, but just so this confusion doesn't come up again without obvious decisions made.

File: sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs (hunk 4 above)
Comment (chlowell) [reply sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs]: Are you imagining changing the builder API by combining the traits or having it take an object implementing both, or changing this implementation to remove the copy?

Comment (heaths) [reply sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs]: I'm not recommending any particular course of action. How often will an `OnRequest` and an `OnChallenge` implementation be different? Should we maybe optimize for that case now where the builder takes a `T` that implements both? The typestate builder pattern would let us have it both ways.

Comment (chlowell) [reply sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs]: The only real use case I know of today is like Key Vault's: using a challenge to discover parameters for use in all future authentications. This scenario requires implementing both traits and sharing state between them--let me know if you want to discuss why this is so and whether a simpler design is possible--so I expect SDK devs will typically implement them on the same type. However, I don't want to require them to do that or make alternative approaches painful because other SDKs have supported a scenario that would require only one of these traits and we may eventually want to support something similar in Rust.

> The typestate builder pattern would let us have it both ways.

Can you please elaborate on this?

Comment (heaths) [reply sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs]: As discussed offline, I thought about this more last night and this pattern is fine. It's not the most idiomatic pattern, sure, but it's also not a "true public API" that *users* of the SDK will use, and even very few - only KV now - will use in the org. Just keep it as-is.

File: sdk/core/typespec_client_core/src/http/request/mod.rs [hunk 7]
```diff
@@ -67,6 +67,18 @@ impl Body {
...
     }
 
+    /// Takes the body, leaving an empty body in its place.
+    pub fn take(&mut self) -> Body {
+        match self {
+            Body::Bytes(_) => std::mem::replace(self, Body::Bytes(Bytes::new())),
+            #[cfg(not(target_arch = "wasm32"))]
+            Body::SeekableStream(_) => std::mem::replace(
+                self,
+                Body::SeekableStream(Box::new(BytesStream::new_empty())),
```
Comment (heaths) [inline sdk/core/typespec_client_core/src/http/request/mod.rs:77]: Oh, I didn't realize that existed. Nice!

File: sdk/keyvault/azure_security_keyvault_certificates/src/clients.rs [hunk 8]
```diff
@@ -2,22 +2,94 @@
...
+/// Options used when creating a [`CertificateClient`]
+#[derive(Clone, SafeDebug)]
+pub struct CertificateClientOptions {
+    /// The API version to use for this operation.
+    pub api_version: String,
+    /// Allows customization of the client.
+    pub client_options: ClientOptions,
+    /// Controls whether the client requires the resource specified in authentication
+    /// challenges to match the Key Vault or Managed HSM domain. True by default.
+    pub verify_challenge_resource: Option<bool>,
```
Comment (heaths) [inline sdk/keyvault/azure_security_keyvault_certificates/src/clients.rs:37]: I'm torn on this being an `Option<bool>`. Can you think of any reason where `None` is interesting if we default to `true` (or even `false`)? I don't think this adds value, even though it follows our guidelines (which aren't hard and fast - "they're more like...guidelines").

Comment (heaths) [reply sdk/keyvault/azure_security_keyvault_certificates/src/clients.rs:37]: As discussed offline, let's just keep it like this, `Option<bool>`. While we can't think of any good scenario where this adds value, it does follow guidelines and most other client and client method options don't have non-optional types. Maybe never useful, but at least consistent.

File: sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs (hunk 3 above)
Comment (jhendrixMSFT) [reply sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs]: Wait why is this in `lib.rs`?  The emitter doesn't write it there.

Comment (chlowell) [reply sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs]: This is handwritten, and since moved to client.rs

Comment (jhendrixMSFT) [reply sdk/keyvault/azure_security_keyvault_certificates/src/lib.rs]: Clarified in https://github.com/Azure/typespec-rust/issues/782
