### PR TITLE
Runtime update of total blob size using content_range header

### LINKED ISSUE #239: Wrong remaining range in blob streaming leads to panic
I'm trying to read read a blob using mostly the example provided in this repo.
However, I seem to be hitting a bug in calculating the remaining range:

```rust
    let storage_account_client =
        StorageAccountClient::new_access_key(http_client.clone(), &account, &master_key);
    let storage_client = storage_account_client.as_storage_client();
    let blob_client = storage_client
        .as_container_client("<container>")
        .as_blob_client("<blob>");

    let response = blob_client.get().execute().await?;
    let mut stream = Box::pin(blob_client.get().stream(64));

    while let Some(value) = stream.next().await {
        println!("received {:?} bytes", value?.data.len());
    }
```
Specifically, when the chunk size is larger than the entire content:

```
remaining: bytes=0-18446744073709551614
start: 0, end: 64
received 40 bytes
remaining: bytes=64-39
start: 64, end: 40
thread 'main' panicked at 'attempt to subtract with overflow', 
/home/radu/projects/src/github.com/Azure/azure-sdk-for-rust/sdk/core/src/request_options/range.rs:23:9
```

When setting the chunk size to 32:

```
remaining: bytes=0-18446744073709551614
start: 0, end: 32
received 32 bytes
remaining: bytes=32-39
start: 32, end: 40
received 8 bytes
```

The issue seems to stem from the way the remaining range is calculated:

https://github.com/Azure/azure-sdk-for-rust/blob/8d275a30e7cd857e38809c651516fc21e51c5ba0/sdk/storage/src/blob/blob/requests/get_blob_builder.rs#L103-L107

### PR DESCRIPTION
**Pull request by MindFlavor**
Fixes #239. There is also a specific E2E test to avoid this to happen again.

This also moves the `content_range` header parsing in a separate module.

### CODE REVIEW

File: sdk/core/src/errors.rs [hunk 1]
```diff
@@ -18,8 +18,10 @@ pub enum ParsingError {
 
 #[derive(Debug, Clone, PartialEq, thiserror::Error)]
 pub enum ParseError {
-    #[error("Split not found")]
-    SplitNotFound,
+    #[error("Expected token {} not found", 0)]
+    TokenNotFound(String),
+    #[error("Split {} not found", 0)]
```
Comment (rylev) [inline sdk/core/src/errors.rs:23]: nit: should the token be printed inside of `'` characters? It might make it easier to read.

File: sdk/core/src/request_options/content_range.rs [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+        };
+
+        let v = remaining.split('-').collect::<Vec<_>>();
+        if v.len() != 2 {
+            return Err(ParseError::SplitNotFound('-'));
+        }
+
+        let start = v[0].parse()?;
+
+        let v = v[1].split('/').collect::<Vec<_>>();
```
Comment (rylev) [inline sdk/core/src/request_options/content_range.rs:55]: 2 nits: 
* The name `v` is very non-descriptive and used quite a bit over nearly 15 lines of code. It is also shadowed. I would prefer a more descriptive name. 
* I would just use the iterator itself instead of allocating a vector. It's roughly the same amount of code but avoids an allocation.

**Review by rylev — APPROVED** [review]
Just some nits. I'll let you decide if you want to fix them before merging.  😃

File: sdk/storage/src/core/errors.rs [hunk 3]
```diff
@@ -66,3 +68,9 @@ impl From<azure_core::errors::ParsingError> for AzureStorageError {
         AzureStorageError::ParsingError(err)
     }
 }
+
+impl From<azure_core::errors::ParseError> for AzureStorageError {
+    fn from(err: azure_core::errors::ParseError) -> AzureStorageError {
```
Comment (ctaggart) [inline sdk/storage/src/core/errors.rs:73]: You can remove this is you just add `#[from]` above.

Comment (MindFlavor) [reply sdk/storage/src/core/errors.rs:73]: Nice! Changed 👍

File: sdk/core/src/request_options/content_range.rs (hunk 2 above)
Comment (MindFlavor) [reply sdk/core/src/request_options/content_range.rs:55]: Good idea, especially not allocating is nice! 👍

**Review by ctaggart — APPROVED** [review]
