### PR TITLE
Disabled AMQP connection tests on OSX

### LINKED ISSUE #2887: Some AMQP tests are flaky on macOS
For the past week or two, we've had some PR checks fail on macOS e.g.,

```text
---- connection::tests::amqp_connection_close stdout ----

thread 'connection::tests::amqp_connection_close' panicked at sdk/core/azure_core_amqp/src/connection.rs:306:18:
called `Result::unwrap()` on an `Err` value: Error { context: Custom(Custom { kind: Io, error: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" } }) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- connection::tests::amqp_connection_open stdout ----

thread 'connection::tests::amqp_connection_open' panicked at sdk/core/azure_core_amqp/src/connection.rs:276:18:
called `Result::unwrap()` on an `Err` value: Error { context: Custom(Custom { kind: Io, error: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" } }) }

---- connection::tests::amqp_connection_close_with_error stdout ----

thread 'connection::tests::amqp_connection_close_with_error' panicked at sdk/core/azure_core_amqp/src/connection.rs:323:18:
called `Result::unwrap()` on an `Err` value: Error { context: Custom(Custom { kind: Io, error: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" } }) }


failures:
    connection::tests::amqp_connection_close
    connection::tests::amqp_connection_close_with_error
    connection::tests::amqp_connection_open
```

Seems to be that, on macOS - but not consistently - the loopback is rejected. It'd be nice to figure out why and fix/work around it (probably not a production code issue, I imagine); but, we could also just disable these tests on macOS as well if they serve little value while being flaky.

### PR DESCRIPTION
**Pull request by LarryOsterman**
Fixes #2887

### CODE REVIEW

File: sdk/core/azure_core_amqp/src/connection.rs [hunk 1]
```diff
@@ -264,6 +264,10 @@ mod tests {
         );
     }
 
+    // On OSX, there is a periodic issue where loopback TCP connections fail.
```
Comment (LarryOsterman) [inline sdk/core/azure_core_amqp/src/connection.rs]:
```suggestion
```
