### PR TITLE
Standardize on time::Duration and time::OffsetDateTime for time elements

### LINKED ISSUE #2711: Rust generator should reference `Duration` and `OffsetDateTime` from azure_core, and not `time::`/`std::time`
### Bug Title

Currently the rust generator uses `time::OffsetDateTime` rather than `azure_core::OffsetDateTime`. This means that all generated crates need to have a workspace dependency on the `time` crate.

### Crate Name

azure_core

### Crate Version

0.24.0

### Description

_No response_

### Steps to Reproduce

Compile the code.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/Azure/azure-sdk-for-rust/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by LarryOsterman**
Fixes #2711 

Updated all code to reflect this:
- Removed references to `time::Duration` and `std::time::Duration` 
- Renamed `typespec_client_core::date` to `typespec_client_core::time` (and reexported as `azure_core::time` instead of `azure_core::date`)
- Updated all generated code to reflect the change.

### CODE REVIEW

File: sdk/identity/azure_identity/src/lib.rs [hunk 1]
```diff
@@ -59,8 +59,8 @@ struct EntraIdErrorResponse {
 #[serde(default)]
 struct EntraIdTokenResponse {
     token_type: String,
-    expires_in: u64,
-    ext_expires_in: u64,
+    expires_in: i64,
```
Comment (chlowell) [inline sdk/identity/azure_identity/src/lib.rs:65]:
```suggestion
    // these are i64 to avoid conversion when calling Duration::seconds
    // (real values are unsigned)
    expires_in: i64,
```

**Review by vincenttran-msft — APPROVED** [review]
Changes look good to me for Storage.

File: sdk/typespec/typespec_client_core/src/async_runtime/tokio_runtime.rs [hunk 2]
```diff
@@ -17,10 +18,11 @@ impl AsyncRuntime for TokioRuntime {
...
-        &self,
-        duration: std::time::Duration,
-    ) -> Pin<Box<dyn std::future::Future<Output = ()> + Send>> {
-        Box::pin(::tokio::time::sleep(duration))
+    fn sleep(&self, duration: Duration) -> Pin<Box<dyn std::future::Future<Output = ()> + Send>> {
+        Box::pin(::tokio::time::sleep(
+            duration
+                .try_into()
+                .expect("Failed to convert duration to tokio format"),
+        ))
```
[the remark this answers is not in the document]
Comment (LarryOsterman) [reply sdk/typespec/typespec_client_core/src/async_runtime/tokio_runtime.rs:26]: In this case, the panic is expected - if you specify a negative duration, that is a clear developer error.

File: sdk/typespec/typespec_client_core/src/async_runtime/standard_runtime.rs [hunk 3]
```diff
@@ -191,7 +187,7 @@ impl Future for Sleep {
             let duration = self.duration;
             self.get_mut().signal = Some(signal.clone());
             thread::spawn(move || {
-                thread::sleep(duration);
+                thread::sleep(duration.try_into().expect("Duration conversion failed"));
                 signal.store(true, Ordering::Release);
                 waker.wake();
```
[the remark this answers is not in the document]
Comment (LarryOsterman) [reply sdk/typespec/typespec_client_core/src/async_runtime/standard_runtime.rs:192]: In this case the panic is expected - negative sleep durations are a programming error on the part of the developer.

File: sdk/typespec/typespec_client_core/CHANGELOG.md [hunk 4]
```diff
@@ -4,11 +4,13 @@
 
 ### Features Added
 
--   Added `get_async_runtime()` and `set_async_runtime()` to allow customers to replace
-    the default asynchronous runtime with another.
+- Added `get_async_runtime()` and `set_async_runtime()` to allow customers to replace
+the default asynchronous runtime with another.
```
Comment (heaths) [inline sdk/typespec/typespec_client_core/CHANGELOG.md:8]: Interesting. What changed on your machine the last PR and this one?

File: sdk/typespec/typespec_client_core/src/time/mod.rs [hunk 5]
```diff
@@ -121,22 +120,22 @@ pub fn to_last_state_change(date: &OffsetDateTime) -> String {
 
 /// Create a duration from the number of minutes.
 pub fn duration_from_minutes(minutes: u64) -> Duration {
-    Duration::from_secs(minutes * 60)
+    Duration::minutes(i64::try_from(minutes).unwrap_or(i64::MAX))
```
Comment (heaths) [inline sdk/typespec/typespec_client_core/src/time/mod.rs]: Given that `minutes` (and other values below) are unsigned, I ponder we should actually just `unwrap()` here and panic if it fails. Defaulting to `i64::MAX` for, example, days could be catastrophic! Better to fail than hang until the heat death of our solar system.

File: sdk/core/azure_core/Cargo.toml [hunk 6]
```diff
@@ -27,7 +27,11 @@ sha2 = { workspace = true, optional = true }
 tokio = { workspace = true, optional = true }
 tracing.workspace = true
 typespec = { workspace = true, features = ["http", "json"] }
-typespec_client_core = { workspace = true, features = ["derive", "http", "json"] }
+typespec_client_core = { workspace = true, features = [
```
Comment (heaths) [inline sdk/core/azure_core/Cargo.toml:30]: Do you have the TOML extension installed? Mine hadn't done this. If you do and it was formatted this way, cool. Just odd since it should be consistent. The TOML extension is one of our recommended ones.

File: sdk/core/azure_core_amqp/CHANGELOG.md [hunk 7]
```diff
@@ -6,6 +6,8 @@
 
 ### Breaking Changes
 
+- Converted all `Duration` references to be `azure_core::Duration`.
```
Comment (heaths) [inline sdk/core/azure_core_amqp/CHANGELOG.md]: Wouldn't that be?
```suggestion
- Converted all `Duration` references to be `azure_core::time::Duration`.
```

File: sdk/eventhubs/azure_messaging_eventhubs/CHANGELOG.md [hunk 8]
```diff
@@ -6,6 +6,8 @@
 
 ### Breaking Changes
 
+- Converted all `Duration` types to `azure_core::Duration`
```
Comment (heaths) [inline sdk/eventhubs/azure_messaging_eventhubs/CHANGELOG.md]:
```suggestion
- Converted all `Duration` types to `azure_core::time::Duration`
```

File: sdk/identity/azure_identity/CHANGELOG.md [hunk 9]
```diff
@@ -7,6 +7,8 @@
 ### Breaking Changes
 
 - Replaced `azure_core::process::Executor` with `azure_identity::process::Executor`.
+- Converted all `Duration` types to `azure_core::Duration`
```
Comment (heaths) [inline sdk/identity/azure_identity/CHANGELOG.md]:
```suggestion
- Converted all `Duration` types to `azure_core::time::Duration`
```

I'll not repeat from here on.

**Review by heaths — CHANGES_REQUESTED** [review]
Let's panic on a couple of those conversions; otherwise, just a few nits to consider.

File: sdk/typespec/typespec_client_core/CHANGELOG.md (hunk 4 above)
Comment (LarryOsterman) [reply sdk/typespec/typespec_client_core/CHANGELOG.md:8]: Different machine - this was made from my home machine, the other from my devbox.

There's some setting that changes the indentation - the markdown checker flagged this on my home machine.

File: sdk/typespec/typespec_client_core/src/time/mod.rs (hunk 5 above)
Comment (LarryOsterman) [reply sdk/typespec/typespec_client_core/src/time/mod.rs]: I was wondering the same thing, TBH. I'll change it to be .unwrap().

File: sdk/core/azure_core/Cargo.toml (hunk 6 above)
Comment (LarryOsterman) [reply sdk/core/azure_core/Cargo.toml:30]: Yes I do have the TOML extension on my machine.

**Review by analogrelay — APPROVED** [review]
Cosmos changes look good

File: sdk/typespec/typespec_client_core/src/time/mod.rs (hunk 5 above)
Comment (LarryOsterman) [reply sdk/typespec/typespec_client_core/src/time/mod.rs]: Hmm, the only way the `i64::try_from` fails is if you're over `i64::MAX`, so clamping to MAX is more accurate. But I think unwrapping is still the right solution.

File: sdk/typespec/typespec_client_core/CHANGELOG.md (hunk 4 above)
Comment (heaths) [reply sdk/typespec/typespec_client_core/CHANGELOG.md:8]: On whichever machine originally put the spaces in, can you check which formatter claims ownership of markdown files? Would be good to figure out how to prevent flipping back and forth. I'd rather standardize on markdown-lint just because Microsoft Learn does as well, so we'd share formatting with official doc policies.

Comment (heaths) [reply sdk/typespec/typespec_client_core/CHANGELOG.md:8]: We talked offline, so re-resolving this (it wasn't blocking anyway).

**Review by heaths — APPROVED** [review]
