### PR TITLE
Get final state from pollers

### LINKED ISSUE #2757: Return final resource from Poller
Splitting up #2458 into different tasks in priority order. This is to add an `IntoFuture` implementation driven by the `Stream` on the `Poller` to refresh the status monitor. We'd probably want `IntoFuture` so we take ownership from the stream, thereby invalidating the stream from that point on.

The `impl<M: StatusMonitor> Future<Output = M::Output> for Poller<M>` would return an `azure_core::Result<M::Output>`[^1] where we'll do a final `GET` based on the [final state designation](https://azure.github.io/typespec-azure/docs/libraries/azure-core/reference/decorators/#@Azure.Core.useFinalStateVia) - or just return the already-deserialized result from the status monitor if defined according to [current guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#the-status-monitor-resource) - if `PollerStatus::Succeeded`. For any other terminal state we'd return an `azure_core::Error`.

We may want to add an `azure_core::error::ErrorKind::Canceled` for user- or service-initiated cancellations. This wouldn't be if the dev canceled the `Future` by dropping it, mind you. It would correspond to `PollerStatus::Canceled` and may be actionable if a caller can distinguish the LRO was cancelled.

[^1]: Exact design is open to change, but this it the POR implementation.

### PR DESCRIPTION
**Pull request by heaths**
Resolves #2757

### CODE REVIEW

**Comment by RickWinter** [comment]
@heaths The doc comments should be made. Do you want to accept the recommendations or do you want to push updates from your branch?

File: sdk/core/azure_core/examples/core_poller.rs [hunk 1]
```diff
@@ -55,11 +101,20 @@ async fn test_core_poller() -> Result<(), Box<dyn std::error::Error>> {
     test_poller().await
 }
 
+#[tokio::test]
+async fn test_core_poller_stream() -> Result<(), Box<dyn std::error::Error>> {
```
Comment (LarryOsterman) [inline sdk/core/azure_core/examples/core_poller.rs:105]: Dead code? I don't see this called, did I miss it?

File: sdk/core/azure_core/src/http/poller.rs [hunk 2]
```diff
@@ -437,50 +581,92 @@ enum State<N> {
...
+            // Flow 'make_request' and target_tx through to avoid cloning
+            Some((item, (next_state, make_request, target_tx)))
         },
-    )
+    );
+
+    let target = Box::new(async move {
+        match target_rx.await {
+            Ok(fut) => fut.await,
+            Err(_) => Err(crate::Error::new(
```
Comment (LarryOsterman) [inline sdk/core/azure_core/src/http/poller.rs]: I take it that the error here isn't interesting?

File: sdk/core/azure_core/src/http/poller.rs [hunk 3]
```diff
@@ -437,50 +581,92 @@ enum State<N> {
...
+                ErrorKind::Other,
+                "poller completed without sending target response",
```
Comment (LarryOsterman) [inline sdk/core/azure_core/src/http/poller.rs]: Shouldn't this indicate some kind of failure rather than just "completed without sending a response"?

File: sdk/core/typespec_client_core/src/http/format.rs [hunk 4]
```diff
@@ -14,14 +14,22 @@ use serde::de::DeserializeOwned;
 /// This is just a marker trait, it has no methods.
 /// Instead, the method to actually perform the deserialization is defined in the [`DeserializeWith`] trait.
 /// This trait is parameterized by a type that implements the [`Format`] trait.
-pub trait Format: std::fmt::Debug {}
+pub trait Format: std::fmt::Debug {
+    /// Deserialize
+    fn deserialize<T: DeserializeOwned, S: AsRef<[u8]>>(body: S) -> crate::Result<T>;
```
Comment (LarryOsterman) [inline sdk/core/typespec_client_core/src/http/format.rs:19]: I don't think this is a marker trait any more, update the comment?

File: sdk/keyvault/azure_security_keyvault_certificates/src/clients.rs [hunk 5]
```diff
@@ -135,6 +129,7 @@ impl CertificateClient {
 
                 let ctx = options.method_options.context.clone();
                 let pipeline = pipeline.clone();
+                let api_version = api_version.clone();
                 async move {
                     let rsp: RawResponse = pipeline.send(&ctx, &mut request, None).await?;
```
Comment (LarryOsterman) [inline sdk/keyvault/azure_security_keyvault_certificates/src/clients.rs]: Do you need to type qualify the `rsp` variable here?

File: sdk/keyvault/azure_security_keyvault_certificates/src/clients.rs [hunk 6]
```diff
@@ -225,14 +250,19 @@ impl CertificateClient {
...
         let pipeline = self.pipeline.clone();
+
         let mut url = self.endpoint.clone();
         let mut path = String::from("certificates/{certificate-name}/pending");
         path = path.replace("{certificate-name}", certificate_name);
         url = url.join(&path)?;
         url.query_pairs_mut()
             .append_pair("api-version", &self.api_version);
+
+        let api_version = self.api_version.clone();
```
Comment (LarryOsterman) [inline sdk/keyvault/azure_security_keyvault_certificates/src/clients.rs:261]: `api_version` doesn't appear to be used beyond line 265, do you need to clone it twice?

File: sdk/core/azure_core/examples/core_poller.rs (hunk 1 above)
Comment (heaths) [reply sdk/core/azure_core/examples/core_poller.rs:105]: It's a test. 😉

File: sdk/core/azure_core/src/http/poller.rs (hunk 3 above)
Comment (heaths) [reply sdk/core/azure_core/src/http/poller.rs]: It's an apt description, and it's in an error. Much like Go, prefacing with "failed" is often unnecessary. Maybe I can reword a little.

File: sdk/keyvault/azure_security_keyvault_certificates/src/clients.rs (hunk 6 above)
Comment (heaths) [reply sdk/keyvault/azure_security_keyvault_certificates/src/clients.rs:261]: Yes, because we have to move captures, so we can't reference `self`.

File: sdk/keyvault/azure_security_keyvault_certificates/src/clients.rs (hunk 5 above)
Comment (heaths) [reply sdk/keyvault/azure_security_keyvault_certificates/src/clients.rs]: No. I think the emitter was doing this in some other client methods from where some of this code was originally copied; though, IIRC, I noticed that a while back and Joel or Anton fixed it since it doesn't do that now.
