### PR TITLE
add new_http_client & fix cosmos_client

### LINKED ISSUE #273: cosmos create_database unable to get pipeline in cosmos e2e tests
This `unwrap()` is panicking when running `cargo test --features test_e2e` for cosmos`.

```
     Running tests\attachment_00.rs (C:\Users\cataggar\io\azure-sdk-for-rust\target\debug\deps\attachment_00-d3a656dafad6c073.exe)     

running 1 test
test attachment ... FAILED

failures:

---- attachment stdout ----
thread 'attachment' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\cataggar\io\azure-sdk-for-rust\sdk\cosmos\src\clients\cosmos_client.rs:158:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    attachment

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass '--test attachment_00'
```

https://github.com/Azure/azure-sdk-for-rust/blob/8784ea58e16261a80b47cb525edb9808052813a8/sdk/cosmos/src/clients/cosmos_client.rs#L146-L171

### LINKED ISSUE #275: fix & enable HttpClient for Hyper
#230 disabled support for Hyper.

### PR DESCRIPTION
**Pull request by ctaggart**
- make cosmos tests pass again by fixing cosmos_client.rs
Fix #273. From #204, I don't really understand what `TransportStack` is for. This removes it.
- adds `new_http_client()` to simplify creation, reduce `use statements` and simplify dependencies
``` rust
let http_client: Arc<Box<dyn HttpClient>> = Arc::new(Box::new(reqwest::Client::new()));

let http_client = azure_core::new_http_client();
```
- removes the unnecessary `Box` in the `Arc<Box`. It seems to work fine without. Did I miss something? 
- disables checking of Hyper implementation of HttpClient until it is fixed #275

### CODE REVIEW

File: sdk/cosmos/src/clients/cosmos_client.rs [hunk 1]
```diff
@@ -20,18 +22,11 @@ const AZURE_VERSION: &str = "2018-12-31";
 const VERSION: &str = "1.0";
 const TIME_FORMAT: &str = "%a, %d %h %Y %T GMT";
 
-use azure_core::*;
-
-#[derive(Clone, Debug)]
-enum TransportStack {
```
Comment (ctaggart) [inline sdk/cosmos/src/clients/cosmos_client.rs:26]: I don't understand why you would have an `HttpClient` or a `Pipeline`. May be it can this can be reintroduced in a subsequent pull request.

File: sdk/cosmos/src/clients/cosmos_client.rs [hunk 2]
```diff
@@ -51,52 +46,76 @@ impl CosmosOptions {
     }
 }
 
+/// Create a Pipeline from CosmosOptions
+fn new_pipeline_from_options(options: CosmosOptions) -> Pipeline {
```
Comment (rylev) [inline sdk/cosmos/src/clients/cosmos_client.rs:50]: Nit: I personally like keeping the struct definition and the impl together which would mean moving these functions below the `impl` block. That's definitely not a blocker though.

File: .github/workflows/build.yml [hunk 3]
```diff
@@ -34,8 +34,8 @@ jobs:
     - name: check core for wasm
       run: cargo check -p azure_core --target=wasm32-unknown-unknown
 
-    - name: check core for hyper
-      run: cargo check -p azure_core --no-default-features --features enable_hyper
+    # - name: check core for hyper
```
Comment (rylev) [inline .github/workflows/build.yml:37]: Why can't this run?

**Review by rylev — APPROVED** [review]
Just have one question.

File: sdk/cosmos/src/clients/cosmos_client.rs (hunk 2 above)
Comment (ctaggart) [reply sdk/cosmos/src/clients/cosmos_client.rs:50]: I'm fine with either. I'll change it to be in the impl.
