### PR TITLE
CosmosDB: support for changing  AuthorizationToken in pipeline

### LINKED ISSUE #337: CosmosClient should propagate the new AuthorizationToken to the AuthorizationPolicy
As seen in #331, the `permission_token_usage` test fails because the change of `AuthorizationToken` does not get propagated to the new `AuthorizationPolicy`. 
What happens is that the "old" code uses the new token while the "new" one (the one using the `AuthorizationPolicy`) does not.

### PR DESCRIPTION
**Pull request by MindFlavor**
CosmosDB crate allows to change the `AuthorizationToken` without having to recreate the client(s). This is useful for quickly switching security context. 
The relevant code didn't account for the new pipeline architecture. This PR fixes that (so now even the `permission_token_usage` test case works as expected).

Fixes #337.

### CODE REVIEW

File: sdk/cosmos/src/clients/cosmos_client.rs [hunk 1]
```diff
@@ -134,7 +134,16 @@ impl CosmosClient {
 
     /// Set the auth token used
     pub fn auth_token(&mut self, auth_token: AuthorizationToken) {
-        self.auth_token = auth_token;
+        // TODO: To remove once everything uses the AutorizationPolicy
+        self.auth_token = auth_token.clone();
+
+        // we replace the AuthorizationPolicy. This is
+        // the last-1 policy by construction.
```
Comment (rylev) [inline sdk/cosmos/src/clients/cosmos_client.rs:141]: This seems pretty error prone... I wonder if there's a better way to do it... Perhaps something like this could be better:

```rust
  /// Set the auth token used
    pub fn auth_token(&mut self, auth_token: AuthorizationToken) {
        self.auth_token = auth_token.clone();

        let new_auth_policy: Arc<dyn azure_core::Policy<CosmosContext>> =
            Arc::new(crate::AuthorizationPolicy::new(auth_token));
        use std::any::Any;
        let auth_policy = self
            .pipeline_mut()
            .policies_mut()
            .iter_mut()
            .find(|p| (**p).type_id() == TypeId::of::<AuthorizationPolicy>())
            .unwrap(); // TODO: add auth policy if one doesn't exist?
        std::mem::replace(auth_policy, new_auth_policy);
    }
```
I've not tested whether this works, but I think it should.

Comment (MindFlavor) [reply sdk/cosmos/src/clients/cosmos_client.rs:141]: Yes it is error prone, unfortunately we forego the type safe approach so these problems are bound to happen. 
In this instance, I think we should get away with the simpler code since:

1. The only place we construct the pipeline is `new_pipeline_from_options`.
2. In `new_pipeline_from_options`, we explicitly add the `AuthorizationPolicy` as last retry policy (penultimate position).

Since there is no way to construct a pipeline without an `AuthorizationPolicy` at the penultimate position my prosed code will always work.

At the other hand, your code is safer but it would correctly work on a buggy pipeline (`AuthorizationPolicy` must be the last retry policy for it to work properly) so I think it's a moot point.

What about an assert? Maybe a `debug_assert` that gets removed from production code? 
The assert should enforce that the swapped policy is indeed an `AuthorizationPolicy`.

**Review by rylev — APPROVED** [review]
