### PR TITLE
fix default credential builder flags

### LINKED ISSUE #525: DefaultAzureCredentialBuilder is created with the wrong default flags
`DefaultAzureCredentialBuilder` is created with the `include_{environment,managed_identity,cli}` flags set to false, and there is no way to set them to true.

An older version of this code set them to true in `::new()`, but this was replaced with `Self::default()`, which doesn't work, because the default value of a bool is false.

### PR DESCRIPTION
**Pull request by polivbr**
fixes #525

### CODE REVIEW

**Review by cataggar — APPROVED** [review]
Thanks! That is a bug from #189, committed on April 1st. I'm confused how this didn't surface earlier.

File: sdk/identity/src/token_credentials/default_credentials.rs [hunk 1]
```diff
@@ -14,7 +14,11 @@ pub struct DefaultAzureCredentialBuilder {
 impl DefaultAzureCredentialBuilder {
     /// Create a new `DefaultAzureCredentialBuilder`
     pub fn new() -> Self {
-        Self::default()
+        Self {
```
Comment (trevor-crypto) [inline sdk/identity/src/token_credentials/default_credentials.rs:17]: I would provide an `impl Default for DefaultAzureCredentialBuilder`, since `new()` takes no parameters anyway.

**Review by trevor-crypto — COMMENTED** [review]
Woops, sorry for introducing this bug! :confounded:

File: sdk/identity/src/token_credentials/default_credentials.rs (hunk 1 above)
Comment (polivbr) [reply sdk/identity/src/token_credentials/default_credentials.rs:16]: Done

**Review by cataggar — APPROVED** [review]

**Comment by thovoll** [comment]
> Thanks! That is a bug from #189, committed on April 1st. I'm confused how this didn't surface earlier.

There are no `tests` or `examples` for `DefaultAzureCredentialBuilder`. @polivbr would you be up for adding something?

**Comment by polivbr** [comment]
Sure. I can add something.

**Comment by polivbr** [comment]
I added some tests and updated the existing default_credentials example to use the builder.

**Comment by thovoll** [comment]
Thanks @polivbr!

**Review by thovoll — APPROVED** [review]

File: sdk/identity/src/token_credentials/default_credentials.rs [hunk 2]
```diff
@@ -3,14 +3,24 @@ use super::{
...
 }
 
+impl Default for DefaultAzureCredentialBuilder {
+    fn default() -> Self {
+        Self {
+            include_environment_credential: true,
+            include_managed_identity_credential: true,
+            include_cli_credential: true,
+        }
+    }
```
Comment (bmc-msft) [inline sdk/identity/src/token_credentials/default_credentials.rs:21]:
```suggestion
        Self::new()
```

Comment (polivbr) [reply sdk/identity/src/token_credentials/default_credentials.rs:21]: I'm not sure what this suggested change would accomplish. Self::new() calls Self::default(), so how would calling Self::new() from the implementation of Default even work?

Comment (bmc-msft) [reply sdk/identity/src/token_credentials/default_credentials.rs:21]: I missed that.  Sorry.

**Review by cataggar — APPROVED** [review]
